### ISSUE TITLE
Errors on installing requirements.txt

### ISSUE THREAD

**Issue by x81kilo** [Skiller9090/Lucifer#49]
Sorry I am new to installing programs and not a coder.  On install I tried both pip and pip3 to try and install on two ubuntu systems.

Errors are below if you can kindly advise -- thanks in advance

[~/Downloads/Lucifer]

└─$ sudo pip3 install -r requirements.txt                           

Collecting Pillow~=8.2.0 (from -r requirements.txt (line 1))

  Downloading Pillow-8.2.0.tar.gz (47.9 MB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.9/47.9 MB 9.5 MB/s eta 0:00:00

  Preparing metadata (setup.py) ... done

Collecting pybrake~=1.0.3 (from -r requirements.txt (line 2))

  Using cached pybrake-1.0.6.tar.gz (35 kB)

  Preparing metadata (setup.py) ... done

Collecting pyyaml~=5.4.0 (from -r requirements.txt (line 3))

  Using cached PyYAML-5.4.1.tar.gz (175 kB)

  Installing build dependencies ... done

  Getting requirements to build wheel ... error

  error: subprocess-exited-with-error

  

  × Getting requirements to build wheel did not run successfully.

  │ exit code: 1

  ╰─> [54 lines of output]

      running egg_info

      writing lib3/PyYAML.egg-info/PKG-INFO

      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt

      writing top-level names to lib3/PyYAML.egg-info/top_level.txt

      Traceback (most recent call last):

        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>

          main()

        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main

          json_out['return_val'] = hook(**hook_input['kwargs'])

                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel

          return hook(config_settings)

                 ^^^^^^^^^^^^^^^^^^^^^

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel

          return self._get_build_requires(config_settings, requirements=['wheel'])

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 295, in _get_build_requires

          self.run_setup()

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 311, in run_setup

          exec(code, locals())

        File "<string>", line 271, in <module>

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/__init__.py", line 103, in setup

          return distutils.core.setup(**attrs)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 184, in setup

          return run_commands(dist)

                 ^^^^^^^^^^^^^^^^^^

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 200, in run_commands

          dist.run_commands()

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands

          self.run_command(cmd)

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 968, in run_command

          super().run_command(command)

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command

          cmd_obj.run()

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py", line 321, in run

          self.find_sources()

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py", line 329, in find_sources

          mm.run()

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py", line 550, in run

          self.add_defaults()

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py", line 588, in add_defaults

          sdist.add_defaults(self)

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/command/sdist.py", line 102, in add_defaults

          super().add_defaults()

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults

          self._add_defaults_ext()

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext

          self.filelist.extend(build_ext.get_source_files())

                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "<string>", line 201, in get_source_files

        File "/tmp/pip-build-env-pcbfybkg/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__

          raise AttributeError(attr)

      AttributeError: cython_sources

      [end of output]

  

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.

│ exit code: 1

╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[Lucifer_Errors.txt](https://github.com/user-attachments/files/15510456/Lucifer_Errors.txt)

**Comment by MIHAWK1699** [comment]
I am facing the same issue.
Please help someone!!!
